import { ServiceProduct } from '@/types';

export const DEFAULT_DOCS_PRODUCTS: ServiceProduct[] = [
  {
    id: 'docs-1',
    title: 'CNH em Cartão PVC',
    description: 'Versão compacta em PVC para organização pessoal e apresentação rápida no dia a dia.',
    price: 39.9,
    category: 'license',
    requiredDocuments: ['CNH em PDF ou imagem', 'Foto do titular', 'Nome completo'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-2',
    title: 'CRLV em PVC',
    description: 'Documento veicular em cartão resistente para uso prático, carteira e porta-documentos.',
    price: 34.9,
    category: 'bureaucracy',
    requiredDocuments: ['CRLV em PDF', 'Placa do veículo', 'Nome do proprietário'],
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-3',
    title: 'Carteira Estudantil em PVC',
    description: 'Modelo personalizado para identificação acadêmica com acabamento durável e impressão nítida.',
    price: 29.9,
    category: 'license',
    requiredDocuments: ['Nome completo', 'Foto 3x4', 'Instituição de ensino', 'Curso ou série'],
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-4',
    title: 'Credencial Empresarial em PVC',
    description: 'Cartão de identificação corporativa para equipes, parceiros e controle interno de acesso.',
    price: 24.9,
    category: 'insurance',
    requiredDocuments: ['Nome do colaborador', 'Cargo', 'Foto', 'Logo da empresa'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-5',
    title: 'Cartão SUS ou Convênio em PVC',
    description: 'Cartão prático para manter dados essenciais sempre acessíveis em um formato mais resistente.',
    price: 27.9,
    category: 'bureaucracy',
    requiredDocuments: ['Arquivo do cartão atual', 'Nome completo', 'Data de nascimento'],
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
];
