import { ServiceProduct } from '@/types';

export const DEFAULT_DOCS_PRODUCTS: ServiceProduct[] = [
  {
    id: 'docs-1',
    title: 'CNH em Cartão PVC',
    description: 'Versão compacta em PVC produzida a partir da CNH oficial em PDF ou imagem com QR Code, para organização pessoal e apresentação rápida no dia a dia.',
    price: 39.9,
    category: 'license',
    requiredDocuments: ['CNH em PDF ou imagem com QR Code', 'Foto do titular', 'Nome completo'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-2',
    title: 'CRLV em PVC',
    description: 'Documento veicular em cartão resistente, produzido a partir do CRLV oficial para uso prático em carteira e porta-documentos.',
    price: 34.9,
    category: 'bureaucracy',
    requiredDocuments: ['CRLV em PDF', 'Placa do veículo', 'Nome do proprietário'],
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-3',
    title: 'Carteira Estudantil em PVC',
    description: 'Modelo personalizado para identificação acadêmica com acabamento durável, impressão nítida e leitura rápida.',
    price: 29.9,
    category: 'license',
    requiredDocuments: ['Nome completo', 'Foto 3x4', 'Instituição de ensino', 'Curso ou série'],
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-4',
    title: 'Credencial Empresarial em PVC',
    description: 'Cartão de identificação corporativa para equipes, parceiros, eventos e controle interno de acesso.',
    price: 24.9,
    category: 'insurance',
    requiredDocuments: ['Nome do colaborador', 'Cargo', 'Foto', 'Logo da empresa'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-5',
    title: 'Cartão SUS ou Convênio em PVC',
    description: 'Cartão prático para manter dados essenciais sempre acessíveis em um formato mais resistente e fácil de carregar.',
    price: 27.9,
    category: 'bureaucracy',
    requiredDocuments: ['Arquivo do cartão atual', 'Nome completo', 'Data de nascimento'],
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-6',
    title: 'Licença de Pescador Amador em PVC',
    description: 'Versão em PVC baseada no registro de pesca amadora/esportiva para organização do pescador e apresentação rápida na rotina.',
    price: 34.9,
    category: 'license',
    requiredDocuments: ['Licença ou registro do pescador amador', 'CPF', 'Nome completo'],
    image: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-7',
    title: 'RGP Pescador Profissional em PVC',
    description: 'Cartão em PVC baseado no Registro Geral da Atividade Pesqueira do pescador profissional para uso prático e identificação rápida.',
    price: 39.9,
    category: 'license',
    requiredDocuments: ['Comprovante ou certificado do RGP profissional', 'CPF', 'Nome completo', 'Foto do titular'],
    image: 'https://images.unsplash.com/photo-1494412685616-a5d310fbb07d?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-8',
    title: 'Registro de Embarcação de Pesca em PVC',
    description: 'Versão compacta em PVC baseada na documentação de embarcação de pesca para consulta rápida em campo e organização do proprietário.',
    price: 42.9,
    category: 'bureaucracy',
    requiredDocuments: ['Documento da embarcação de pesca', 'Nome da embarcação', 'Número de inscrição', 'Nome do responsável'],
    image: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-9',
    title: 'TIE em PVC',
    description: 'Título de Inscrição de Embarcação em formato PVC com leitura do documento base e seleção dos dados essenciais para caber no cartão padrão.',
    price: 39.9,
    category: 'bureaucracy',
    requiredDocuments: [
      'TIE ou TIEM em PDF/imagem com QR Code',
      'Número de inscrição',
      'Nome da embarcação',
      'Tipo da embarcação',
      'Nome do proprietário',
      'CPF/CNPJ do proprietário',
      'Tipo de propulsão',
      'Quantidade de motores',
      'Área de navegação',
      'Data de validade',
    ],
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-10',
    title: 'CHA Arrais-Amador em PVC',
    description: 'Carteira de Habilitação de Amador, categoria Arrais-Amador, em versão PVC para acesso rápido e uso em rotina náutica.',
    price: 37.9,
    category: 'license',
    requiredDocuments: ['CHA ou comprovante de habilitação Arrais-Amador', 'Nome completo', 'CPF'],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-11',
    title: 'CHA Motonauta em PVC',
    description: 'Carteira de Habilitação de Amador, categoria Motonauta, em PVC para organização pessoal e apresentação prática.',
    price: 37.9,
    category: 'license',
    requiredDocuments: ['CHA ou comprovante de habilitação Motonauta', 'Nome completo', 'CPF'],
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-12',
    title: 'CIN em Cartão PVC',
    description: 'Versão em PVC baseada na Carteira de Identidade Nacional para manter seus dados sempre organizados em formato compacto.',
    price: 32.9,
    category: 'license',
    requiredDocuments: ['CIN em PDF ou imagem', 'CPF', 'Nome completo'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-13',
    title: 'CPF Digital em PVC',
    description: 'Cartão em PVC baseado no CPF digital para uso diário, organização pessoal e acesso rápido aos dados principais.',
    price: 24.9,
    category: 'bureaucracy',
    requiredDocuments: ['CPF digital ou comprovante oficial', 'Nome completo', 'Data de nascimento'],
    image: 'https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-14',
    title: 'Carteira de Trabalho Digital em PVC',
    description: 'Versão em PVC inspirada na CTPS Digital para organização, identificação e apresentação dos dados principais do trabalhador.',
    price: 34.9,
    category: 'bureaucracy',
    requiredDocuments: ['Print ou PDF da CTPS Digital', 'CPF', 'Nome completo'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-15',
    title: 'Título de Eleitor em PVC',
    description: 'Versão em PVC baseada no e-Título ou no título eleitoral para quem quer manter os dados sempre à mão em um formato resistente.',
    price: 29.9,
    category: 'bureaucracy',
    requiredDocuments: ['e-Título ou título eleitoral', 'Nome completo', 'Número do título'],
    image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-16',
    title: 'Certificado de Dispensa de Incorporação em PVC',
    description: 'Cartão em PVC baseado no CDI para manter a identificação militar complementar em formato compacto e durável.',
    price: 31.9,
    category: 'bureaucracy',
    requiredDocuments: ['CDI em PDF ou imagem', 'Nome completo', 'CPF'],
    image: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
  {
    id: 'docs-17',
    title: 'Certificado de Reservista em PVC',
    description: 'Versão em PVC baseada no Certificado de Reservista para organização pessoal e acesso rápido aos dados do documento.',
    price: 31.9,
    category: 'bureaucracy',
    requiredDocuments: ['Certificado de Reservista em PDF ou imagem', 'Nome completo', 'CPF'],
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=800',
    businessSegment: 'docs',
  },
];
